### ISSUE TITLE
Gestion des liens_auteurs sur les objets

### ISSUE THREAD

**Issue by phenix-factory** [bystrano/objecteur#4]
Il n'y a aucune gestion et c'est dommage

**Comment by bystrano** [comment]
Tu as testé ça comment ? J'ai créé un squelette `test.html`comme ça :

``` php
<?php
$objecteur = charger_fonction('objecteur', 'inc');
var_dump($objecteur(array(
  'objet' => 'article',
  'options' => array(
      'titre' => "Mon nouvel article",
      'id_parent' => 3,
  ),
),true));
```

et j'appelle ensuite l'url `spip.php?page=test`. Voici ce que je constate : 
- Si je suis logué comme webmestre, l'article créé a bien mon utilisateur comme auteur.
- Si je ne suis pas logué, l'appel à la page crée un nouvel article sans auteur.

Ça n'est évidement pas idéal, mais c'est plutôt un problème d'autorisations que d'auteur, puisque l'API `editer_objet` semble se charger des auteurs toute seule. D'ailleurs avant de tester j'aurais pensé qu'elle se chargerait des autorisations aussi…

**Comment by bystrano** [comment]
Et hop ! fc896f976cccb12d95b0617d09336b20c9fe42d5 ajoute une vérification des autorisations.

**Comment by phenix-factory** [comment]
Ça me semble bien de prendre en compte le système d'autorisation de SPIP.

Par contre, ne serait il pas judicieux de tester d'abord l’existence
d'une function autoriser_creer avant de tout bloquer. On doit pouvoir
utiliser charger_fonction pour le test.
Si l'objet n'a pas de de fonction autoriser_creer on peu en déduire que
la création est libre.

Je me demande aussi si une API pour créer une autorisation propre à
objecteur ne serai pas une bonne idée, genre
autoriser_objecteur_monObjet afin d'autoriser l'objecteur à faire des
choses qu'un utilisateur ne pourrais pas faire en temps normal.
L'objecteur ce voulant être un moyen "safe" pour créer des objets, cela
me semble pertinent. Ou pas.

Didier

**Comment by bystrano** [comment]
> Par contre, ne serait il pas judicieux de tester d'abord l’existence d'une function autoriser_creer avant de tout bloquer. On doit pouvoir utiliser charger_fonction pour le test. Si l'objet n'a pas de de fonction autoriser_creer on peu en déduire que la création est libre.

De nouveau, je veux bien un exemple de code qui ne produit pas le résultat désiré… Je viens d'essayer : 

``` php
<?php
include_spip('inc/autoriser');
var_dump(autoriser('manger', 'crepes'));
```

et ça retourne `true`. Il me semble que dans SPIP, tout ce qui n'est pas interdit est autorisé, ça ne servirait donc à rien de faire des tests sur l'existence des fonctions `autoriser_creer_*`.
