### ISSUE TITLE
Objecteur et mes_fonctions.php

### ISSUE THREAD

**Issue by phenix-factory** [bystrano/objecteur#7]
Quand on lance objecteur depuis `mes_fonctions.php` on a une fatal error malgré que l'`include_spip` soit bien présent.
Faire l'`include_spip` dans `mes_fonctions` ne change rien non plus. 

![capture du 2015-04-21 17 18 57](https://cloud.githubusercontent.com/assets/1810149/7255615/a85af476-e84a-11e4-8c76-68579a7732d1.png)

**Comment by phenix-factory** [comment]
Je crois que j'ai comprit pourquoi cela ne fonctionne pas dans mes_fonctions.php.

Dans le fichier d'autorisation, il y a ce code (L43):

``` php
// mes_fonctions peut aussi declarer des autorisations, donc il faut donc le charger
if ($f = find_in_path('mes_fonctions.php')) {
    global $dossier_squelettes;
    include_once(_ROOT_CWD . $f);
}
```

Du coup, si on fait un `include_spip('inc/autoriser')` depuis mes_fonctions, on créé une boucle d'inclusion, vu qu'on exécute directement le code depuis mes_fonctions.
On remercie au passage PHP de faire comme si de rien n'était.

Pas vraiment de solution pour contourner ce problème.

**Comment by bystrano** [comment]
Bien vu !

> On remercie au passage PHP de faire comme si de rien n'était.

Merci PHP d'ignorer silencieusement les inclusions qui se mordent la queue ! Ça rends le débugage bien plus fun ! Où est le plaisir si le message d'erreur pointe vers la bonne ligne ? :-)

**Comment by bystrano** [comment]
Mais au final je pense aussi qu'il n'y a rien à faire. On demande à `mes_fonctions.php` deux choses contradictoire : pouvoir participer à la définition de la fonction `autoriser`, et en même temps pouvoir l'utiliser.
Ça n'est même pas une limitation inhérente à SPIP, c'est vouloir quelque chose de logiquement impossible.
